name: daily-devcard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.2.0
        with:
          user_id: ${{ secrets.DEVCARD_ID }}
          commit_branch: devcard
          commit_message: "chore: update ${filename}"

  wide:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.2.0
        with:
          user_id: ${{ secrets.DEVCARD_ID }}
          type: wide
          commit_filename: wide.png
          commit_branch: devcard
          commit_message: "chore: update ${filename}"
