name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: thelime1/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_notable: yes
          plugin_notable_from: all
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_posts: yes
          plugin_posts_sources: dev.to
          plugin_posts_limit: 5
          config_options: >
            user: thelime1
