name: daily-metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metric
          committer_message: "build: update `${filename}`"
          user: TheLime1
          template: classic
          base: header, activity, community
          base_indepth: yes
          config_octicon: yes
          config_twemoji: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit,pull_request,issue

  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metric
          committer_message: "build: update `${filename}`"
          user: TheLime1
          template: classic
          base: ""
          config_display: large
          config_output: svg
          filename: achievements.svg
          repositories_batch: 5
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
